### PR TITLE
chore: move to JavaScript Standard Style

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by NielsSkovgaard** [comment]
Hi @Trott 
I see you changed let to const here: **for (const key in opts.multicharmap) {**
Unfortunately, this broke our application when running in IE11. The error is:
**SCRIPT1053: Const must be initialized**
Could this be fixed e.g. by rolling back to using let, please?

**Comment by Trott** [comment]
Sure, I"ll get a fix version out in a few minutes, if all goes well. (Then I guess I'll see if I can add IE11 to our karma tests in GitHub Actions or something....)

**Comment by Trott** [comment]
@NielsSkovgaard Version 3.3.1 is published with this fixed. Let me know if that works for you. Thanks for reporting the problem.

**Comment by NielsSkovgaard** [comment]
@Trott Thanks for solving this so fast 😊

**Comment by NielsSkovgaard** [comment]
Hi @Trott . I just tested this and identified something else in this library that IE 11 doesn't support, which is backticks (`) i.e. template strings, which are used on three different lines.

**Comment by Trott** [comment]
> Hi @Trott . I just tested this and identified something else in this library that IE 11 doesn't support, which is backticks (`) i.e. template strings, which are used on three different lines.

Fix published in 3.3.2. Since I don't have IE11 to test on, a comment here confirming that it fixed your problem would be very much appreciated.

I'm setting stuff up with Sauce Labs so I can get the tests here running on IE11 so hopefully this type of breakage won't happen again.

**Comment by NielsSkovgaard** [comment]
Thanks, @Trott. Looks like it's working in IE11 now 👍

**Pull request merged**
